spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/respondent/**
          - id: researcher-service
            uri: lb://researcher-service
            predicates:
              - Path=/researcher/**
          - id: admin-service
            uri: lb://admin-service
            predicates:
              - Path=/admin/**
server:
  port: 8060

#Eureka configurations
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/